-- Аккаунты для Alex Johnson (первый пользователь)
INSERT INTO accounts (id, user_id, name, type, currency_id, credit_limit, current_balance, include_in_total_balance,
                      default_account, bank_id, card_number1, card_number2, card_number3, card_number4, savings_account,
                      archive_account)
VALUES (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'alex.johnson@example.com'),
        'Основной расчетный счет',
        1,
        'USD',
        NULL,
        5250.75,
        true,
        true,
        (SELECT id FROM banks WHERE display_name = 'Chase Bank' LIMIT 1),
        '4539',
        '1488',
        '2034',
        '5678',
        false,
        false),
       (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'alex.johnson@example.com'),
        'Накопительный счет',
        2,
        'USD',
        NULL,
        15200.00,
        true,
        false,
        (SELECT id FROM banks WHERE display_name = 'Bank of America' LIMIT 1),
        '5112',
        '8945',
        '3267',
        '9012',
        true,
        false),
       (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'alex.johnson@example.com'),
        'Кредитная карта',
        3,
        'EUR',
        5000.00,
        -1250.50,
        true,
        false,
        (SELECT id FROM banks WHERE display_name = 'HSBC' LIMIT 1),
        '6011',
        '4923',
        '7856',
        '3456',
        false,
        false);

-- Аккаунты для Maria Garcia (второй пользователь)
INSERT INTO accounts (id, user_id, name, type, currency_id, credit_limit, current_balance, include_in_total_balance,
                      default_account, bank_id, card_number1, card_number2, card_number3, card_number4, savings_account,
                      archive_account)
VALUES (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'maria.garcia@example.com'),
        'Main Checking',
        1,
        'EUR',
        NULL,
        3200.00,
        true,
        true,
        (SELECT id FROM banks WHERE display_name = 'Santander' LIMIT 1),
        '4111',
        '2222',
        '3333',
        '4444',
        false,
        false),
       (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'maria.garcia@example.com'),
        'Savings Account',
        2,
        'EUR',
        NULL,
        8500.00,
        true,
        false,
        (SELECT id FROM banks WHERE display_name = 'BNP Paribas' LIMIT 1),
        '5555',
        '6666',
        '7777',
        '8888',
        true,
        false),
       (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'maria.garcia@example.com'),
        'Cash Wallet',
        4,
        'EUR',
        NULL,
        450.25,
        true,
        false,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        false,
        false);

-- Аккаунты для David Smith (третий пользователь)
INSERT INTO accounts (id, user_id, name, type, currency_id, credit_limit, current_balance, include_in_total_balance,
                      default_account, bank_id, card_number1, card_number2, card_number3, card_number4, savings_account,
                      archive_account)
VALUES (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'david.smith@example.com'),
        'Primary Account',
        1,
        'GBP',
        NULL,
        7800.00,
        true,
        true,
        (SELECT id FROM banks WHERE display_name = 'Barclays' LIMIT 1),
        '1111',
        '2222',
        '3333',
        '4444',
        false,
        false),
       (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'david.smith@example.com'),
        'Investment Portfolio',
        5,
        'USD',
        NULL,
        25000.00,
        false,
        false,
        (SELECT id FROM banks WHERE display_name = 'Deutsche Bank' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        true,
        false),
       (uuid_generate_v4(),
        (SELECT id FROM users WHERE email = 'david.smith@example.com'),
        'Credit Line',
        3,
        'GBP',
        10000.00,
        -3200.00,
        true,
        false,
        (SELECT id FROM banks WHERE display_name = 'Royal Bank' LIMIT 1),
        '9999',
        '8888',
        '7777',
        '6666',
        false,
        false);